### PR TITLE
Add-on - Badge Icon added to let user know profile can be changed

### PR DESCRIPTION
**Pull request by gbudjeakp**
badgeicon

### CODE REVIEW

**Comment by Tojonirina4** [comment]
I was wondering if the display of this icon should be controlled by the edit button? Or should we remove the edit button as it is not doing any action now?

**Comment by gbudjeakp** [comment]
> I was wondering if the display of this icon should be controlled by the edit button? Or should we remove the edit button as it is not doing any action now?

I'm not sure but we could ask the rest of the team

**Comment by BoomBoomRay** [comment]
I think the badge Icon looks better.

**Review by BoomBoomRay — APPROVED** [review]

**Review by newCodeWriter — COMMENTED** [review]
I like the badge icon idea. It looks good. I would say remove the edit button as suggested. However, we need to decide if edits are going to be made in Account Settings or if we need to remove that link from the profile if we are using the badge icon.

**Comment by Tojonirina4** [comment]
I agree with the option to put the edit option in account setting. It will make more sense

**Pull request merged**
